version: "3.5"

services:
  vm-charts-prod:
    build: .
    ports:
      - 80:80
    container_name: vm-charts
    networks:
      - vm-charts-network
  vm-charts-local:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    container_name: vm-charts
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - vm-charts-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VIRTUAL_HOST=vm-charts.local.com
    depends_on:
      - nginx-proxy

  nginx-proxy-front:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - vm-charts-network

networks:
  vm-charts-network:
    name: vm-charts-network